---
title: ltp
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Material theme based on <a href="http://materializecss.com">Materialize.css</a>
  for jekyll sites

'
baseurl: "/matjek"
url: https://prasadltp.github.io
permalink: "/:year/:month/:day/:title"
repository: ShawnTeoh/matjek
paginate: 5
github_profile: https://github.com/ShawnTeoh
user: John Doe
user_email: john@doe.com
contact_url: https://goo.gl/tVljbV
google_tracking_id: UA-96359860-1
google_site_verification: UA-96359860-1
disqus_shortname: matjek
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
future: true
