---
title: ltp
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 
baseurl: "/matjek"
url: https://prasadltp.github.io
permalink: "/:year/:month/:day/:title"
repository: prasadltp/ltp
paginate: 5
github_profile: https://github.com/prasadltp/
user: prasadltp
user_email: prasad@letstalkpayments.com
contact_url: 
google_tracking_id: 
google_site_verification: 
disqus_shortname: ltp
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
future: true
